WindowManager:
    HomeWindow:
    PredictorWindow:

<HomeWindow>:
    name: "home"
    FloatLayout:
        canvas.before:
            Color:
                rgba: 0.1, 0.1, 0.1, 1  # Dark gray background
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            id: background
            size_hint: 10, 10
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1  # Light gray background
                Rectangle:
                    pos: self.pos
                    size: self.size

        GridLayout:
            cols: 1
            size_hint: None, None
            size_hint_min_y: root.height * 0.2
            pos_hint: {"center_x": 0.5, "center_y": 0.7}
            Label:
                text: "Health Monitor (working design)"
                font_size: root.height * 0.04
                halign: 'right'
                valign: 'center'

        GridLayout:
            cols: 2
            spacing: root.width * 0.05
            padding: root.width * 0.05
            size_hint: None, None
            size_hint_min_y: root.height * 0.5
            pos_hint: {"center_x": 0.5, "center_y": 0.4}
            Button:
                text: "Predictor"
                background_color: 1, 0, 0, 1  # Red button
                size_hint: None, None
                size: root.width * 0.2, root.height * 0.1
                on_release:
                    app.root.current = "predictor"
            Button:
                text: "Some features"
                background_color: 0, 1, 0, 1  # Green button
                size_hint: None, None
                size: root.width * 0.2, root.height * 0.1
            Button:
                text: "Some features"
                background_color: 0, 0, 1, 1  # Blue button
                size_hint: None, None
                size: root.width * 0.2, root.height * 0.1
            Button:
                text: "Some features"
                background_color: 1, 1, 0, 1  # Yellow button
                size_hint: None, None
                size: root.width * 0.2, root.height * 0.1
            Button:
                text: "Some features"
                background_color: 1, 0, 1, 1  # Magenta button
                size_hint: None, None
                size: root.width * 0.2, root.height * 0.1
            Button:
                text: "Some features"
                background_color: 0, 1, 1, 1  # Cyan button
                size_hint: None, None
                size: root.width * 0.2, root.height * 0.1

<PredictorWindow>:
    name: "predictor"
    FloatLayout:
        canvas.before:
            Color:
                rgba: 0.1, 0.1, 0.1, 1  # Dark gray background
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            id: background
            size_hint: 10, 10
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1  # Light gray background
                Rectangle:
                    pos: self.pos
                    size: self.size

        Button:
            text: "Back"
            background_color: 0.2, 0.2, 0.2, 1  # Dark gray button
            size_hint: None, None
            size: root.width * 0.1, root.height * 0.05
            pos_hint: {"x": 0.05, "y": 0.9}
            on_release: app.root.current = "home"

        RelativeLayout:
            cols: 1
            BoxLayout:
                orientation: "vertical"
                ScrollView:
                    id: symptom_scroll
                    size_hint: (1, None)
                    size: (root.width, root.height - 200)
                    GridLayout:
                        id: symptom_container
                        cols: 1
                        size_hint_y: None
                        height: self.minimum_height

            Button:
                text: "Predict"
                background_color: 1, 0, 0, 1  # Red button
                on_press: root.predict_disease()
                size_hint: None, None
                size: root.width * 0.2, root.height * 0.1
                pos: root.width * 0.8, root.height * 0.4

        Label:
            id: disease_label
            text: ""
            size_hint_y: None
            height: dp(40)
            pos_hint: {"top": 0.9, "left": 0.1}
